apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 22222
    protocol: TCP
    targetPort: 22222
    nodePort: 31177
  selector:
    app: helloworld
  type: NodePort
