kind: Service
apiVersion: v1
metadata:
  name: prometheus
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31190
  selector:
    app: prometheus
  type: NodePort
